# Generated by Django 5.2.5 on 2025-10-02 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividad4', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrador',
            old_name='nombre_completo',
            new_name='Nombre_completo',
        ),
        migrations.RenameField(
            model_name='administrador',
            old_name='email',
            new_name='correo',
        ),
    ]
