# Generated by Django 5.2.5 on 2025-10-02 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividad4', '0002_rename_nombre_completo_administrador_nombre_completo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrador',
            old_name='Nombre_completo',
            new_name='nombre_completo',
        ),
    ]
