# Generated by Django 5.2.5 on 2025-10-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividad4', '0003_rename_nombre_completo_administrador_nombre_completo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='carnet',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='carrera',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
