# Generated by Django 5.2.5 on 2025-10-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividad4', '0005_publicacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='estudiante',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='publicacion',
            old_name='aprobada',
            new_name='autorizada',
        ),
        migrations.RenameField(
            model_name='publicacion',
            old_name='fecha',
            new_name='fecha_creacion',
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
